port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  # listen: 0.0.0.0:53
  ipv6: false # 当此选项为 false 时, AAAA 请求将返回空

  # 以下填写的 DNS 服务器将会被用来解析 DNS 服务的域名
  # 仅填写 DNS 服务器的 IP 地址
  default-nameserver:
    - 223.5.5.5
    - 1.2.4.8
    #- 114.114.114.114
    #- 119.29.29.29
  enhanced-mode: redir-host # 或 fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 (CIDR 形式)
  # use-hosts: true # 查询 hosts 并返回 IP 记录

  # 在以下列表的域名将不会被解析为 fake ip，这些域名相关的解析请求将会返回它们真实的 IP 地址
  # fake-ip-filter:
  #   - '*.lan'
  #   - localhost.ptlogin2.qq.com

  # 支持 UDP / TCP / DoT / DoH 协议的 DNS 服务，可以指明具体的连接端口号。
  # 所有 DNS 请求将会直接发送到服务器，不经过任何代理。
  # Clash 会使用最先获得的解析记录回复 DNS 请求
  nameserver:
    #如果你有自建的DNS服务器或专用网络的DNS服务器可在托管链接添加如 &dns=9.9.9.9 参数（9.9.9.9替换成你要自定义的DNS，注 意，此DNS必须有效，否则将导致出错无法使用），自定义DNS将出现以下方

    #默认提供DoT / DoH 协议的DNS
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
    - tls://223.6.6.6
    #- https://dns.alidns.com/dns-query
    #- https://v6.rubyfish.cn/dns-query
    #- https://rubyfish.cn/dns-query
    #- https://223.6.6.6/dns-query
    #- https://doh.360.cn/dns-query
    #- tls://223.5.5.5
    #- tls://dns.alidns.com
    #- tls://13800000000.rubyfish.cn
    #- tls://dot.360.cn
    #- 223.5.5.5
    #- 119.29.29.29

  # 当 fallback 参数被配置时, DNS 请求将同时发送至上方 nameserver 列表和下方 fallback 列表中配置的所有 DNS 服务器.
  # 当解析得到的 IP 地址的地理位置不是 CN 时，clash 将会选用 fallback 中 DNS 服务器的解析结果。
  fallback:
    - https://1.0.0.1/dns-query
    - https://dns.google/dns-query
    - tls://8.8.4.4
    #- https://cloudflare-dns.com/dns-query
    #- https://1.1.1.1/dns-query
    #- https://dns.twnic.tw/dns-query
    #- tls://1.0.0.1
    #- tls://dns.adguard.com:853

  # 如果使用 nameserver 列表中的服务器解析的 IP 地址在下方列表中的子网中，则它们被认为是无效的，
  # Clash 会选用 fallback 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 true 且 IP 地址的地理位置为 CN 时，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 当 fallback-filter.geoip 为 false, 如果解析结果在 fallback-filter.ipcidr 范围内，
  # Clash 会选用 nameserver 列表中配置 DNS 服务器解析得到的结果。
  #
  # 采取以上逻辑进行域名解析是为了对抗 DNS 投毒攻击。
  fallback-filter:
    geoip: false
    ipcidr:
    # - 240.0.0.0/4